print("VNESITE 3 CELOŠTEVILSKE VREDNOSTI TAKO, DA ZA VSAKO VREDNOST KLIKNITE ENTER. PROGRAM VAM BO SPROTI ZA VSAKO ŠTEVILO IZPISAL NJENO VREDNOST TER NJEN TIP.")

a = int(input("VNESITE PRVO CELO ŠTEVILO TER KLIKNITE ENTER!"))
print(a,type(a))

b = int(input("VNESITE DRUGO CELO ŠTEVILO TER KLIKNITE ENTER!"))
print(b,type(b))

c = int(input("VNESITE TRETJE CELO ŠTEVILO TER KLIKNITE ENTER!"))
print(c,type(c))
if(b==a and c <= a): print("VREDNOSTI SO ZADOSTILE POGOJEM NALOGE!!!")
else: print("VREDNOSTI NISO ZADOSTILE POGOJEM NALOGE.")