n = input("VNESI NEKO CELO ŠTEVILO!")
print("VREDNOST SPREMENLJIVKE n JE",n,". PRIPADA VRSTI TIPA ",type(n),".") 

print("V TEM DELU KODE PRETVORIMO VREDNOST SPREMELJIVKE n V FLOAT VREDNOST.")
n = float(n)

print("SEDEJ IZPIŠEMO VREDNOST SPREMENLJIVKE n, KI JE: ",n," TER NJEN TIP:", type(n))