print("TO JE SEŠTEVALNIK DVEH ŠTEVIL, VNESITE VSAKO ŠTEVILO POSEBEJ TER ZA VSAKIM ŠTEVILOM KLIKNITE TIPKO ENTER. PROGRAM VAM BO IZPISAL NJUNO VSOTO.")
a = float(input("VNESITE PRVO ŠTEVILO!"))
b = float(input("VNESITE DRUGO ŠTEVILO!"))
x = a + b
print("NJUNA VSOTA JE ",x," !!!")

